name: Daily Random Commit

on:
  schedule:
    - cron: "25 12 * * *"
      timezone: "Asia/Kolkata"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make random change
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 100000))
          echo "Random update: $RANDOM_NUMBER" >> daily-activity.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add daily-activity.txt
          git commit -m "Daily random update"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Push changes
        run: |
          git push origin main
